import Head from "next/head";
import styled from "styled-components";
import ChatRoom from "../components/ChatRoom";
import CreateChatPopUp from "../components/CreateChatPopUp";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp clone Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Sidebar />
        <ChatRoom />
        {/* <CreateChatPopUp /> */}
      </Container>
    </div>
  );
}

const Container = styled.div`
  display: flex;
  height: 100vh;
  width: 100%;
  position: relavite;
`;
