import Head from "next/head";
import { useEffect } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import styled from "styled-components";
import ChatRoom from "../components/ChatRoom";
import CreateChatPopUp from "../components/CreateChatPopUp";
import Sidebar from "../components/Sidebar";
import { auth } from "../firebase";
import { useGlobalState } from "../globalStateProvider";

export default function Home() {
  const [user] = useAuthState(auth);
  const [{ displayCreatePopup }, dispatch] = useGlobalState();
  useEffect(() => {
    user && dispatch({ type: "SET_USER", user: user });
  }, [user]);
  return (
    <div>
      <Head>
        <title>WhatsApp clone Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Sidebar />
        <ChatRoom />
        {displayCreatePopup && <CreateChatPopUp />}
      </Container>
    </div>
  );
}

const Container = styled.div`
  display: flex;
  height: 100vh;
  width: 100%;
  position: relavite;
`;
